apiVersion: 1

datasources:
  - name: WoWS_PostgreSQL
    type: postgres
    uid: wows_postgres
    access: proxy
    url: ${DB_HOST}:5432
    database: ${DB_NAME}
    user: ${DB_USER}
    isDefault: true
    secureJsonData:
      password: ${DB_PASSWORD}
    jsonData:
      sslmode: require
      maxOpenConns: 5
      maxIdleConns: 2
      connMaxLifetime: 14400
      postgresVersion: 1500
